/*
 * librAIry API
 * Learn about [librAIry](http://librairy.github.io/) or follow the account `@librairy_fw` on twitter.     This research project receives funding from the European Commission's Seventh Framework Programme.Activity ICT (FP7-ICT-2013.8.1)  Grant agreement no: 611383 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: librairy.framework@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Reference;

/**
 * ContainerStats
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-19T14:34:01.940Z")
public class ContainerStats {
  @SerializedName("container")
  private Reference container = null;

  @SerializedName("documents")
  private Long documents = null;

  @SerializedName("parts")
  private Long parts = null;

  @SerializedName("similarities")
  private Long similarities = null;

  @SerializedName("subdomains")
  private Long subdomains = null;

  @SerializedName("topics")
  private Long topics = null;

  public ContainerStats container(Reference container) {
    this.container = container;
    return this;
  }

   /**
   * Get container
   * @return container
  **/
  @ApiModelProperty(example = "null", value = "")
  public Reference getContainer() {
    return container;
  }

  public void setContainer(Reference container) {
    this.container = container;
  }

  public ContainerStats documents(Long documents) {
    this.documents = documents;
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDocuments() {
    return documents;
  }

  public void setDocuments(Long documents) {
    this.documents = documents;
  }

  public ContainerStats parts(Long parts) {
    this.parts = parts;
    return this;
  }

   /**
   * Get parts
   * @return parts
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getParts() {
    return parts;
  }

  public void setParts(Long parts) {
    this.parts = parts;
  }

  public ContainerStats similarities(Long similarities) {
    this.similarities = similarities;
    return this;
  }

   /**
   * Get similarities
   * @return similarities
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSimilarities() {
    return similarities;
  }

  public void setSimilarities(Long similarities) {
    this.similarities = similarities;
  }

  public ContainerStats subdomains(Long subdomains) {
    this.subdomains = subdomains;
    return this;
  }

   /**
   * Get subdomains
   * @return subdomains
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSubdomains() {
    return subdomains;
  }

  public void setSubdomains(Long subdomains) {
    this.subdomains = subdomains;
  }

  public ContainerStats topics(Long topics) {
    this.topics = topics;
    return this;
  }

   /**
   * Get topics
   * @return topics
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTopics() {
    return topics;
  }

  public void setTopics(Long topics) {
    this.topics = topics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContainerStats containerStats = (ContainerStats) o;
    return Objects.equals(this.container, containerStats.container) &&
        Objects.equals(this.documents, containerStats.documents) &&
        Objects.equals(this.parts, containerStats.parts) &&
        Objects.equals(this.similarities, containerStats.similarities) &&
        Objects.equals(this.subdomains, containerStats.subdomains) &&
        Objects.equals(this.topics, containerStats.topics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(container, documents, parts, similarities, subdomains, topics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContainerStats {\n");
    
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("    similarities: ").append(toIndentedString(similarities)).append("\n");
    sb.append("    subdomains: ").append(toIndentedString(subdomains)).append("\n");
    sb.append("    topics: ").append(toIndentedString(topics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

