/*
 * librAIry API
 * Learn about [librAIry](http://librairy.github.io/) or follow the account `@librairy_fw` on twitter.     This research project receives funding from the European Commission's Seventh Framework Programme.Activity ICT (FP7-ICT-2013.8.1)  Grant agreement no: 611383 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: librairy.framework@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Domain
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-19T14:34:01.940Z")
public class Domain {
  @SerializedName("creationTime")
  private String creationTime = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Gets or Sets resourceType
   */
  public enum ResourceTypeEnum {
    @SerializedName("SOURCE")
    SOURCE("SOURCE"),
    
    @SerializedName("DOMAIN")
    DOMAIN("DOMAIN"),
    
    @SerializedName("DOCUMENT")
    DOCUMENT("DOCUMENT"),
    
    @SerializedName("ITEM")
    ITEM("ITEM"),
    
    @SerializedName("PART")
    PART("PART"),
    
    @SerializedName("WORD")
    WORD("WORD"),
    
    @SerializedName("ANALYSIS")
    ANALYSIS("ANALYSIS"),
    
    @SerializedName("TOPIC")
    TOPIC("TOPIC"),
    
    @SerializedName("SERIALIZED_OBJECT")
    SERIALIZED_OBJECT("SERIALIZED_OBJECT"),
    
    @SerializedName("TERM")
    TERM("TERM"),
    
    @SerializedName("FILTER")
    FILTER("FILTER"),
    
    @SerializedName("PATH")
    PATH("PATH"),
    
    @SerializedName("FILE")
    FILE("FILE"),
    
    @SerializedName("ANY")
    ANY("ANY");

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("resourceType")
  private ResourceTypeEnum resourceType = null;

  @SerializedName("uri")
  private String uri = null;

  public Domain creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }

  public Domain description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Domain name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Domain resourceType(ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @ApiModelProperty(example = "null", value = "")
  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }

  public void setResourceType(ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
  }

  public Domain uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Domain domain = (Domain) o;
    return Objects.equals(this.creationTime, domain.creationTime) &&
        Objects.equals(this.description, domain.description) &&
        Objects.equals(this.name, domain.name) &&
        Objects.equals(this.resourceType, domain.resourceType) &&
        Objects.equals(this.uri, domain.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationTime, description, name, resourceType, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Domain {\n");
    
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

