/*
 * librAIry API
 * Learn about [librAIry](http://librairy.github.io/) or follow the account `@librairy_fw` on twitter.     This research project receives funding from the European Commission's Seventh Framework Programme.Activity ICT (FP7-ICT-2013.8.1)  Grant agreement no: 611383 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: librairy.framework@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Reference;
import io.swagger.client.model.Score;
import java.util.ArrayList;
import java.util.List;

/**
 * Topic
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-19T14:34:01.940Z")
public class Topic {
  @SerializedName("description")
  private String description = null;

  @SerializedName("documents")
  private Long documents = null;

  @SerializedName("parts")
  private Long parts = null;

  @SerializedName("ref")
  private Reference ref = null;

  @SerializedName("score")
  private Double score = null;

  @SerializedName("words")
  private List<Score> words = new ArrayList<Score>();

  public Topic description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Topic documents(Long documents) {
    this.documents = documents;
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDocuments() {
    return documents;
  }

  public void setDocuments(Long documents) {
    this.documents = documents;
  }

  public Topic parts(Long parts) {
    this.parts = parts;
    return this;
  }

   /**
   * Get parts
   * @return parts
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getParts() {
    return parts;
  }

  public void setParts(Long parts) {
    this.parts = parts;
  }

  public Topic ref(Reference ref) {
    this.ref = ref;
    return this;
  }

   /**
   * Get ref
   * @return ref
  **/
  @ApiModelProperty(example = "null", value = "")
  public Reference getRef() {
    return ref;
  }

  public void setRef(Reference ref) {
    this.ref = ref;
  }

  public Topic score(Double score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }

  public Topic words(List<Score> words) {
    this.words = words;
    return this;
  }

  public Topic addWordsItem(Score wordsItem) {
    this.words.add(wordsItem);
    return this;
  }

   /**
   * Get words
   * @return words
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Score> getWords() {
    return words;
  }

  public void setWords(List<Score> words) {
    this.words = words;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Topic topic = (Topic) o;
    return Objects.equals(this.description, topic.description) &&
        Objects.equals(this.documents, topic.documents) &&
        Objects.equals(this.parts, topic.parts) &&
        Objects.equals(this.ref, topic.ref) &&
        Objects.equals(this.score, topic.score) &&
        Objects.equals(this.words, topic.words);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, documents, parts, ref, score, words);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Topic {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    words: ").append(toIndentedString(words)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

