/*
 * librAIry API
 * Learn about [librAIry](http://librairy.github.io/) or follow the account `@librairy_fw` on twitter.     This research project receives funding from the European Commission's Seventh Framework Programme.Activity ICT (FP7-ICT-2013.8.1)  Grant agreement no: 611383 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: librairy.framework@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ComparisonRequest;
import io.swagger.client.model.ComparisonResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ComparisonsapicontrollerApi
 */
@Ignore
public class ComparisonsapicontrollerApiTest {

    private final ComparisonsapicontrollerApi api = new ComparisonsapicontrollerApi();

    
    /**
     * comparisonsPost
     *
     * Create a new &#x60;Comparison&#x60;. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comparisonsPostUsingPOSTTest() throws ApiException {
        ComparisonRequest comparisonRequest = null;
        ComparisonResult response = api.comparisonsPostUsingPOST(comparisonRequest);

        // TODO: test validations
    }
    
}
